name: first_game
description: "A new Flutter project."
version: 0.0.0
publish_to: 'none'

environment:
  sdk: '>=3.2.6 <4.0.0'
  flutter: ^3.13.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flame: ^1.15.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
